### PR TITLE
Fix #3

### LINKED ISSUE #3: test.bmp output file in SharpNoise.Tests\GraniteTextureTest.cs should be removed after tests
In test _SharpNoise.Tests\GraniteTextureTest.cs_, in `GraniteTexture_SphericalRender` test (the last one), the output file created in:

`bitmap.Save(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "test.bmp"), System.Drawing.Imaging.ImageFormat.Bmp);`

Should be removed after the test end.
Or file created into _temp_ directory.

### PR DESCRIPTION
**Pull request by rthome**
GraniteTexture_SphericalRender unit test leaves files on the desktop

### CODE REVIEW

**Comment by InfiniteProductions** [comment]
Looks like you didn't paid attention to EOL in files, it ends up with the full file seen as modified, hiding the few lines changed. Unfortunate :(.
See [this](http://stackoverflow.com/questions/5009096/files-showing-as-modified-directly-after-git-clone) for more info, especially `* text=auto` needs to be changed.

**Comment by rthome** [comment]
Yes, something must have changed in my setup between when i wrote that code and now. I noticed the EOL screwup only right after i had pushed it, unfortunately :<

**Comment by InfiniteProductions** [comment]
Not on your setup, it comes from some moron working for github (a "double agent" sent by Microsoft probably), unfortunately.
I worked with github desktop client for a while without any trouble, just have some this weekend when committing my changes.

**Comment by rthome** [comment]
How strange. Anyway I disabled the offending line in commit 56b410f.

**Pull request merged**
